-- FROMAGE_DB
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FROMAGE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FROMAGE` DEFAULT CHARACTER SET utf8 ;
USE `FROMAGE` ;

-- -----------------------------------------------------
-- Table `FROMAGE`.`USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`USUARIOS` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`USUARIOS` (
  `Id_usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Perfil` INT NOT NULL,
  PRIMARY KEY (`Id_usuario`))
ENGINE = InnoDB;
--CREATE UNIQUE INDEX `Nombre_UNIQUE` ON `FROMAGE`.`USUARIOS` (`Nombre` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `FROMAGE`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`PRODUCTO` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`PRODUCTO` (
  `id_PRODUCTO` INT NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Calidad` VARCHAR(45) NOT NULL,
  `Id_proveedores` INT NOT NULL,
  `Unidad` VARCHAR(45) NOT NULL,
  `Precio_Venta` INT NOT NULL,
  PRIMARY KEY (`id_PRODUCTO`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `FROMAGE`.`BODEGA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`BODEGA` ;

CREATE TABLE IF NOT EXISTS `FROMAGE`.`BODEGA` (
  `Id_producto` INT NOT NULL,
  `A_venta` INT NULL,
  `Reserva12hrs` INT NULL,
  `A_entrega` INT NULL,
  `PRODUCTO_id_PRODUCTO` INT NOT NULL,
  PRIMARY KEY (`Id_producto`, `PRODUCTO_id_PRODUCTO`),
  CONSTRAINT `fk_BODEGA_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_PRODUCTO`)
    REFERENCES `FROMAGE_VENTAS`.`PRODUCTO` (`id_PRODUCTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE UNIQUE INDEX `Id_producto_UNIQUE` ON `FROMAGE`.`BODEGA` (`Id_producto` ASC) VISIBLE;
CREATE INDEX `fk_BODEGA_PRODUCTO1_idx` ON `FROMAGE`.`BODEGA` (`PRODUCTO_id_PRODUCTO` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `FROMAGE`.`PEDIDOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`PEDIDOS` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`PEDIDOS` (
  `id_PEDIDO` INT NOT NULL,
  `Id_Producto` INT NOT NULL,
  `Id_Clientes` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `FACTURACION_NumFactura` INT NOT NULL,
  `BODEGA_Id_producto` INT NOT NULL,
  `BODEGA_Id_producto1` INT NOT NULL,
  `BODEGA_PRODUCTO_id_PRODUCTO` INT NOT NULL,
  PRIMARY KEY (`id_PEDIDO`, `FACTURACION_NumFactura`, `BODEGA_Id_producto`, `BODEGA_Id_producto1`, `BODEGA_PRODUCTO_id_PRODUCTO`),
  CONSTRAINT `fk_PEDIDOS_BODEGA1`
    FOREIGN KEY (`BODEGA_Id_producto1` , `BODEGA_PRODUCTO_id_PRODUCTO`)
    REFERENCES `FROMAGE_VENTAS`.`BODEGA` (`Id_producto` , `PRODUCTO_id_PRODUCTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_PEDIDOS_BODEGA1_idx` ON `FROMAGE_VENTAS`.`PEDIDOS` (`BODEGA_Id_producto1` ASC, `BODEGA_PRODUCTO_id_PRODUCTO` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `FROMAGE`.`VENDEDORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`VENDEDORES` ;

CREATE TABLE IF NOT EXISTS `FROMAGE`.`VENDEDORES` (
  `Id_vendedor` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `RUT` VARCHAR(10) NOT NULL,
  `PEDIDOS_id_PEDIDO` INT NOT NULL,
  `PEDIDOS_FACTURACION_NumFactura` INT NOT NULL,
  `PEDIDOS_BODEGA_Id_producto` INT NOT NULL,
  PRIMARY KEY (`Id_vendedor`, `PEDIDOS_id_PEDIDO`, `PEDIDOS_FACTURACION_NumFactura`, `PEDIDOS_BODEGA_Id_producto`),
  CONSTRAINT `fk_VENDEDORES_USUARIOS1`
    FOREIGN KEY (`Id_vendedor`)
    REFERENCES `FROMAGE`.`USUARIOS` (`Id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDEDORES_PEDIDOS1`
    FOREIGN KEY (`PEDIDOS_id_PEDIDO` , `PEDIDOS_FACTURACION_NumFactura` , `PEDIDOS_BODEGA_Id_producto`)
    REFERENCES `FROMAGE`.`PEDIDOS` (`id_PEDIDO` , `FACTURACION_NumFactura` , `BODEGA_Id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_VENDEDORES_USUARIOS1_idx` ON `FROMAGE`.`VENDEDORES` (`Id_vendedor` ASC) VISIBLE;
CREATE INDEX `fk_VENDEDORES_PEDIDOS1_idx` ON `FROMAGE`.`VENDEDORES` (`PEDIDOS_id_PEDIDO` ASC, `PEDIDOS_FACTURACION_NumFactura` ASC, `PEDIDOS_BODEGA_Id_producto` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `FROMAGE`.`GdDESPACHO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`GdDESPACHO` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`GdDESPACHO` (
  `Num_GDESPACHO` INT NOT NULL,
  `Id_pedido` INT NOT NULL,
  PRIMARY KEY (`Num_GDESPACHO`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `FROMAGE`.`FACTURAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`FACTURAS` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`FACTURAS` (
  `NumFactura` INT NOT NULL,
  `Id_Pedido` INT NOT NULL,
  `Id_Cliente` INT NOT NULL,
  `Num_Pago_Bancario` VARCHAR(45) NOT NULL,
  `GDESPACHO_Num_GDESPACHO` INT NOT NULL,
  PRIMARY KEY (`NumFactura`, `GDESPACHO_Num_GDESPACHO`),
  CONSTRAINT `fk_FACTURACION_GDESPACHO1`
    FOREIGN KEY (`GDESPACHO_Num_GDESPACHO`)
    REFERENCES `FROMAGE_VENTAS`.`GdDESPACHO` (`Num_GDESPACHO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_FACTURACION_GDESPACHO1_idx` ON `FROMAGE`.`FACTURAS` (`GDESPACHO_Num_GDESPACHO` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `FROMAGE`.`CLIENTES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`CLIENTES` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`CLIENTES` (
  `id_CLIENTES` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `RUT` VARCHAR(10) NOT NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  `Teléfono` VARCHAR(45) NOT NULL,
  `PEDIDO_id_PEDIDO` INT NOT NULL,
  `PEDIDO_FACTURACION_NumFactura` INT NOT NULL,
  `FACTURAS_NumFactura` INT NOT NULL,
  `FACTURAS_GDESPACHO_Num_GDESPACHO` INT NOT NULL,
  PRIMARY KEY (`id_CLIENTES`, `PEDIDO_id_PEDIDO`, `PEDIDO_FACTURACION_NumFactura`, `FACTURAS_NumFactura`, `FACTURAS_GDESPACHO_Num_GDESPACHO`),
  CONSTRAINT `fk_CLIENTES_PEDIDO1`
    FOREIGN KEY (`PEDIDO_id_PEDIDO` , `PEDIDO_FACTURACION_NumFactura`)
    REFERENCES `FROMAGE`.`PEDIDOS` (`id_PEDIDO` , `FACTURACION_NumFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_FACTURAS1`
    FOREIGN KEY (`FACTURAS_NumFactura` , `FACTURAS_GDESPACHO_Num_GDESPACHO`)
    REFERENCES `FROMAGE`.`FACTURAS` (`NumFactura` , `GDESPACHO_Num_GDESPACHO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_CLIENTES_PEDIDO1_idx` ON `FROMAGE`.`CLIENTES` (`PEDIDO_id_PEDIDO` ASC, `PEDIDO_FACTURACION_NumFactura` ASC) VISIBLE;
CREATE INDEX `fk_CLIENTES_FACTURAS1_idx` ON `FROMAGE`.`CLIENTES` (`FACTURAS_NumFactura` ASC, `FACTURAS_GDESPACHO_Num_GDESPACHO` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `FROMAGE`.`PROVEEDORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`PROVEEDORES` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`PROVEEDORES` (
  `id_Proveedores` INT NOT NULL auto increment,
  `Nombre` VARCHAR(45) NOT NULL,
  `RUT` VARCHAR(10) NOT NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  `Teléfono` VARCHAR(45) NOT NULL,
  `Contacto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Proveedores`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `FROMAGE`.`OdCOMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`OdCOMPRA` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`OdCOMPRA` (
  `Id_OC` INT NOT NULL,
  `Id_producto` INT NOT NULL,
  `Id_proveedores` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Fecha_OC` DATE NOT NULL,
  `Fecha_recepcion` DATE NULL,
  `PROVEEDORES_id_Proveedores` INT NOT NULL,
  PRIMARY KEY (`Id_OC`, `PROVEEDORES_id_Proveedores`),
  CONSTRAINT `fk_OdCOMPRA_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDORES_id_Proveedores`)
    REFERENCES `FROMAGE`.`PROVEEDORES` (`id_Proveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_OdCOMPRA_PROVEEDOR1_idx` ON `FROMAGE`.`OdCOMPRA` (`PROVEEDORES_id_Proveedores` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `FROMAGE`.`PRODUCTO_has_OdCOMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`PRODUCTO_has_OdCOMPRA` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`PRODUCTO_has_OdCOMPRA` (
  `PRODUCTO_id_PRODUCTO` INT NOT NULL,
  `OdCOMPRA_Id_OC` INT NOT NULL,
  PRIMARY KEY (`PRODUCTO_id_PRODUCTO`, `OdCOMPRA_Id_OC`),
  CONSTRAINT `fk_PRODUCTO_has_OdCOMPRA_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_id_PRODUCTO`)
    REFERENCES `FROMAGE_VENTAS`.`PRODUCTO` (`id_PRODUCTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_has_OdCOMPRA_OdCOMPRA1`
    FOREIGN KEY (`OdCOMPRA_Id_OC`)
    REFERENCES `FROMAGE`.`OdCOMPRA` (`Id_OC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_PRODUCTO_has_OdCOMPRA_OdCOMPRA1_idx` ON `FROMAGE`.`PRODUCTO_has_OdCOMPRA` (`OdCOMPRA_Id_OC` ASC) VISIBLE;
CREATE INDEX `fk_PRODUCTO_has_OdCOMPRA_PRODUCTO1_idx` ON `FROMAGE`.`PRODUCTO_has_OdCOMPRA` (`PRODUCTO_id_PRODUCTO` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `FROMAGE`.`ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`ROLES` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`ROLES` (
  `id_ROLES` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `importancia` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ROLES`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `FROMAGE`.`DOMINIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`DOMINIOS` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`DOMINIOS` (
  `id_DOMINIO` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `es_singular` TINYINT NULL,
  PRIMARY KEY (`id_DOMINIO`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `FROMAGE`.`OBJETOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`OBJETOS` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`OBJETOS` (
  `id_OBJETOS` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_OBJETOS`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `FROMAGE`.`ROLES_has_DOMINIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`ROLES_has_DOMINIOS` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`ROLES_has_DOMINIOS` (
  `ROLES_id_ROLES` INT NOT NULL,
  `DOMINIOS_id_DOMINIO` INT NOT NULL,
  `privilegios_id_privilegios` INT NULL,
  `ROLES_has_DOMINIOScol` VARCHAR(45) NULL,
  PRIMARY KEY (`ROLES_id_ROLES`, `DOMINIOS_id_DOMINIO`),
  CONSTRAINT `fk_ROLES_has_DOMINIOS_ROLES1`
    FOREIGN KEY (`ROLES_id_ROLES`)
    REFERENCES `FROMAGE`.`ROLES` (`id_ROLES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROLES_has_DOMINIOS_DOMINIOS1`
    FOREIGN KEY (`DOMINIOS_id_DOMINIO`)
    REFERENCES `FROMAGE`.`DOMINIOS` (`id_DOMINIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_ROLES_has_DOMINIOS_DOMINIOS1_idx` ON `FROMAGE`.`ROLES_has_DOMINIOS` (`DOMINIOS_id_DOMINIO` ASC) VISIBLE;
CREATE INDEX `fk_ROLES_has_DOMINIOS_ROLES1_idx` ON `FROMAGE`.`ROLES_has_DOMINIOS` (`ROLES_id_ROLES` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `FROMAGE`.`PRIVILEGIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`PRIVILEGIOS` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`PRIVILEGIOS` (
  `id_PRIVILEGIOS` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `es_singular` TINYINT NULL,
  `ROLES_has_DOMINIOS_ROLES_id_ROLES` INT NOT NULL,
  `ROLES_has_DOMINIOS_DOMINIOS_id_DOMINIO` INT NOT NULL,
  PRIMARY KEY (`id_PRIVILEGIOS`, `ROLES_has_DOMINIOS_ROLES_id_ROLES`, `ROLES_has_DOMINIOS_DOMINIOS_id_DOMINIO`),
  CONSTRAINT `fk_PRIVILEGIOS_ROLES_has_DOMINIOS1`
    FOREIGN KEY (`ROLES_has_DOMINIOS_ROLES_id_ROLES` , `ROLES_has_DOMINIOS_DOMINIOS_id_DOMINIO`)
    REFERENCES `FROMAGE`.`ROLES_has_DOMINIOS` (`ROLES_id_ROLES` , `DOMINIOS_id_DOMINIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_PRIVILEGIOS_ROLES_has_DOMINIOS1_idx` ON `FROMAGE`.`PRIVILEGIOS` (`ROLES_has_DOMINIOS_ROLES_id_ROLES` ASC, `ROLES_has_DOMINIOS_DOMINIOS_id_DOMINIO` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `FROMAGE`.`ACCIONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`ACCIONES` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`ACCIONES` (
  `id_ACCIONES` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ACCIONES`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `FROMAGE`.`USUARIOS_has_ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`USUARIOS_has_ROLES` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`USUARIOS_has_ROLES` (
  `USUARIOS_Id_usuario` INT NOT NULL,
  `ROLES_id_ROLES` INT NOT NULL,
  PRIMARY KEY (`USUARIOS_Id_usuario`, `ROLES_id_ROLES`),
  CONSTRAINT `fk_USUARIOS_has_ROLES_USUARIOS1`
    FOREIGN KEY (`USUARIOS_Id_usuario`)
    REFERENCES `FROMAGE`.`USUARIOS` (`Id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_has_ROLES_ROLES1`
    FOREIGN KEY (`ROLES_id_ROLES`)
    REFERENCES `FROMAGE`.`ROLES` (`id_ROLES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_USUARIOS_has_ROLES_ROLES1_idx` ON `FROMAGE`.`USUARIOS_has_ROLES` (`ROLES_id_ROLES` ASC) VISIBLE;
CREATE INDEX `fk_USUARIOS_has_ROLES_USUARIOS1_idx` ON `FROMAGE`.`USUARIOS_has_ROLES` (`USUARIOS_Id_usuario` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `FROMAGE`.`DOMINIOS_has_OBJETOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`DOMINIOS_has_OBJETOS` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`DOMINIOS_has_OBJETOS` (
  `DOMINIOS_id_DOMINIO` INT NOT NULL,
  `OBJETOS_id_OBJETOS` INT NOT NULL,
  PRIMARY KEY (`DOMINIOS_id_DOMINIO`, `OBJETOS_id_OBJETOS`),
  CONSTRAINT `fk_DOMINIOS_has_OBJETOS_DOMINIOS1`
    FOREIGN KEY (`DOMINIOS_id_DOMINIO`)
    REFERENCES `FROMAGE`.`DOMINIOS` (`id_DOMINIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOMINIOS_has_OBJETOS_OBJETOS1`
    FOREIGN KEY (`OBJETOS_id_OBJETOS`)
    REFERENCES `FROMAGE`.`OBJETOS` (`id_OBJETOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_DOMINIOS_has_OBJETOS_OBJETOS1_idx` ON `FROMAGE`.`DOMINIOS_has_OBJETOS` (`OBJETOS_id_OBJETOS` ASC) VISIBLE;
CREATE INDEX `fk_DOMINIOS_has_OBJETOS_DOMINIOS1_idx` ON `FROMAGE`.`DOMINIOS_has_OBJETOS` (`DOMINIOS_id_DOMINIO` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `FROMAGE`.`PRIVILEGIOS_has_ACCIONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FROMAGE`.`PRIVILEGIOS_has_ACCIONES` ;
CREATE TABLE IF NOT EXISTS `FROMAGE`.`PRIVILEGIOS_has_ACCIONES` (
  `PRIVILEGIOS_id_PRIVILEGIOS` INT NOT NULL,
  `PRIVILEGIOS_ROLES_has_DOMINIOS_ROLES_id_ROLES` INT NOT NULL,
  `PRIVILEGIOS_ROLES_has_DOMINIOS_DOMINIOS_id_DOMINIO` INT NOT NULL,
  `ACCIONES_id_ACCIONES` INT NOT NULL,
  PRIMARY KEY (`PRIVILEGIOS_id_PRIVILEGIOS`, `PRIVILEGIOS_ROLES_has_DOMINIOS_ROLES_id_ROLES`, `PRIVILEGIOS_ROLES_has_DOMINIOS_DOMINIOS_id_DOMINIO`, `ACCIONES_id_ACCIONES`),
  CONSTRAINT `fk_PRIVILEGIOS_has_ACCIONES_PRIVILEGIOS1`
    FOREIGN KEY (`PRIVILEGIOS_id_PRIVILEGIOS` , `PRIVILEGIOS_ROLES_has_DOMINIOS_ROLES_id_ROLES` , `PRIVILEGIOS_ROLES_has_DOMINIOS_DOMINIOS_id_DOMINIO`)
    REFERENCES `FROMAGE`.`PRIVILEGIOS` (`id_PRIVILEGIOS` , `ROLES_has_DOMINIOS_ROLES_id_ROLES` , `ROLES_has_DOMINIOS_DOMINIOS_id_DOMINIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRIVILEGIOS_has_ACCIONES_ACCIONES1`
    FOREIGN KEY (`ACCIONES_id_ACCIONES`)
    REFERENCES `FROMAGE`.`ACCIONES` (`id_ACCIONES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
CREATE INDEX `fk_PRIVILEGIOS_has_ACCIONES_ACCIONES1_idx` ON `FROMAGE`.`PRIVILEGIOS_has_ACCIONES` (`ACCIONES_id_ACCIONES` ASC) VISIBLE;
CREATE INDEX `fk_PRIVILEGIOS_has_ACCIONES_PRIVILEGIOS1_idx` ON `FROMAGE`.`PRIVILEGIOS_has_ACCIONES` (`PRIVILEGIOS_id_PRIVILEGIOS` ASC, `PRIVILEGIOS_ROLES_has_DOMINIOS_ROLES_id_ROLES` ASC, `PRIVILEGIOS_ROLES_has_DOMINIOS_DOMINIOS_id_DOMINIO` ASC) VISIBLE;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
